spring:
  application:
    name: e-commerce-api
  datasource:
    url: jdbc:postgresql://localhost:5433/e_commerce
    username: "postgres"
    password: "postgres"
  flyway:
    locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  freemarker:
    template-loader-path: classpath:/mail-templates/
    charset: UTF-8
    cache: false
  scheduler:
    token-purge:
      cron: 0 0 0 * * *
minio:
  url: http://localhost:9000
  access:
    name: minioadmin
    secret: minioadmin

logging:
  level:
    org:
      springframework:
        web: DEBUG
        security: DEBUG
server:
  servlet:
    session:
      timeout: 20m

app:
  domain: http://localhost:8080
  mail-properties:
    email-confirmation-link-pattern: http://localhost:8080/api/v1/auth/confirm-email?token=%s
    reset-password-link-pattern: http://localhost:8080/api/v1/auth/reset-password/%s