ALTER TABLE users
    ADD COLUMN confirmed BOOLEAN;

CREATE TABLE confirmation_token
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date            TIMESTAMP WITHOUT TIME ZONE,
    last_modified_date      TIMESTAMP WITHOUT TIME ZONE,
    confirmation_token_type VARCHAR(255),
    token                   VARCHAR(255),
    expiration_date         TIMESTAMP WITHOUT TIME ZONE,
    user_id                 BIGINT,
    CONSTRAINT pk_confirmationtoken PRIMARY KEY (id)
);

ALTER TABLE confirmation_token
    ADD CONSTRAINT FK_CONFIRMATIONTOKEN_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);