CREATE TABLE shop
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date       TIMESTAMP WITHOUT TIME ZONE,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    name               VARCHAR(255),
    description        VARCHAR(255),
    address            VARCHAR(255),
    phone              VARCHAR(255),
    main_image         VARCHAR(255),
    owner_id           BIGINT NOT NULL references users (id),
    CONSTRAINT pk_shop PRIMARY KEY (id)
);

CREATE TABLE shop_manager
(
    manager_id BIGINT NOT NULL references users (id),
    shop_id    BIGINT NOT NULL references shop (id)
);
