CREATE TABLE shop
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date       TIMESTAMP WITHOUT TIME ZONE,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    name               VARCHAR(255),
    description        VARCHAR(255),
    address            VARCHAR(255),
    phone              VARCHAR(255),
    main_image         VARCHAR(255),
    CONSTRAINT pk_shop PRIMARY KEY (id)
);


CREATE TABLE shop_staff
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id   BIGINT,
    shop_role VARCHAR(255),
    shop_id   BIGINT,
    CONSTRAINT pk_shopstaff PRIMARY KEY (id)
);

ALTER TABLE shop_staff
    ADD CONSTRAINT FK_SHOPSTAFF_ON_SHOP FOREIGN KEY (shop_id) REFERENCES shop (id);

ALTER TABLE shop_staff
    ADD CONSTRAINT FK_SHOPSTAFF_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);