CREATE TABLE orders
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date       TIMESTAMP WITHOUT TIME ZONE,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    status             VARCHAR(255),
    shop_product_id    BIGINT,
    user_id            BIGINT,
    quantity           INTEGER,
    price              DOUBLE PRECISION,
    total              DOUBLE PRECISION,
    CONSTRAINT pk_orders PRIMARY KEY (id)
);

ALTER TABLE orders
    ADD CONSTRAINT FK_ORDERS_ON_SHOP_PRODUCT FOREIGN KEY (shop_product_id) REFERENCES shop_product (id);

ALTER TABLE orders
    ADD CONSTRAINT FK_ORDERS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);