CREATE TABLE orders
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date       TIMESTAMP WITHOUT TIME ZONE,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    status             VARCHAR(255),
    shop_product_id    BIGINT NOT NULL,
    user_id            BIGINT NOT NULL,
    quantity           INTEGER,
    price              DOUBLE PRECISION,
    total              DOUBLE PRECISION,
    CONSTRAINT pk_orders PRIMARY KEY (id)
);

ALTER TABLE orders
    ADD CONSTRAINT FK_ORDERS_ON_SHOP_PRODUCT FOREIGN KEY (shop_product_id) REFERENCES shop_product (id);

ALTER TABLE orders
    ADD CONSTRAINT FK_ORDERS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);


CREATE TABLE order_status_changes
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date       TIMESTAMP WITHOUT TIME ZONE,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    order_id           BIGINT NOT NULL,
    changed_by_id      BIGINT NOT NULL,
    new_status         VARCHAR(255),
    CONSTRAINT pk_order_status_changes PRIMARY KEY (id)
);

ALTER TABLE order_status_changes
    ADD CONSTRAINT FK_ORDER_STATUS_CHANGES_ON_CHANGED_BY FOREIGN KEY (changed_by_id) REFERENCES shop_staff (id);

ALTER TABLE order_status_changes
    ADD CONSTRAINT FK_ORDER_STATUS_CHANGES_ON_ORDER FOREIGN KEY (order_id) REFERENCES orders (id);